urls.py
from django.conf.urls import url
from . import views

from rest_framework.urlpatterns import format_suffix_patterns

app_name = "jihanki"

urlpatterns = [
    # /
    # /jihanki/*
    url(r'^$',views.index,name="index"),
    url(r'^index/$',views.index,name="subindex"),
    
    url(r'^sell/$',views.SellView.as_view(),name="sellview"),

    # url(r'^sell/post/$',views.sellpost,name="sellpost"),
    # /jihanki/sell
    # url(r'^sell/priv/$',views.sell,name="sell"),

    # /jihanki/buy/post/<product_id>/
    url(r'^buyconfirm/(?P<pk>[0-9]+)/$',views.BuyConfirmView.as_view(),name="buyconfirm"),
    # /jihanki/buy
    url(r'^buy/$',views.BuyView.as_view(),name="buy"),

    url(r'^log/$',views.log,name="log"),

    url(r'^news/$',views.news,name="news"),

    url(r'^payment/in/$',views.PaymentInView.as_view(),name="paymentIn"),

    url(r'^dev/$',views.DevView.as_view(),name="dev"),

    url(r'^payment/out/(?P<pk>[0-9]+)/$',views.PaymentOutView.as_view(),name="paymentOut"),

    url(r'^deleteitem/(?P<pk>[0-9]+)/$',views.DeleteItemView.as_view(),name="deleteItem"),

    url(r'^itemlist/$',views.ItemList.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

templates/jihanki/buy.html
{% extends "base.html" %}

{% block hero %}
<h1>いろいろと買っていきましょう！</h1>
<p>買ってけ買ってけ</p>
{% endblock hero %}

{% block main %}
<div class="row">
    <div class="small-12 large-12 columns">
        <div class="row">
            <div class="mediam-12 columns">
                <h1>買う</h1>
                <h3>買ってけ</h3>
                {% if message %}
                <h1 id="message">{{ message }}</h1>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="small-12 large-12 column">
                {% for item in items %}
                <div class="callout">
                    {% if SELF_FEE %}
                    <h3>{{item.product_name}} : ￥{{item.product_price_with_fee}}</h3>
                    {% else %} {% if item.seller == userdata %}
                    <h3>{{item.product_name}} : ￥{{item.product_price}}</h3>
                    {% else %}
                    <h3>{{item.product_name}} : ￥{{item.product_price_with_fee}}</h3>
                    {% endif %} {% endif %}
                    {#<p>Qt. {{item.product_Quantity}}</p>#}
                    <a href="{% url 'jihanki:buyconfirm' item.id %}" class="button" style="margin:0;margin-right:10px">買う</a>
                    {% if userdata == item.seller %}
                    <form action="{% url 'jihanki:deleteItem' item.id %}" method="POST" style="display:inline-block">
                        {% csrf_token %}
                        <input class="button alert" type="submit" value="削除" style="margin: 0">
                    </form>
                    {#<a href="{% url 'jihanki:deleteItem' item.id %}" class="button alert">削除</a>#}
                    {% endif %}
                </div>
                {% endfor %}
                <a class="button alert" style="margin-top: 50px" href="{% url 'jihanki:index' %}">戻る</a>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

templates/jihanki/buy_confirm.html
{% extends "base.html" %}

{% block hero %}
<h1>いろいろと買っていきましょう！</h1>
<p>買ってけ買ってけ</p>
{% endblock hero %}


{% block main %}

    {% if error %}
        <div class="error">
            <h2>{{error}}</h2>
        </div>
    {% endif %}
    {% if OK%}
    <h3>購入できました！</h3>
    <p>発泡スチロールから持っていってください！</p>
    <a class="button accept" href="{% url 'jihanki:index' %}">戻る</a>

    {% else %}
    <h3>これでOKですか？</h3>
    <form action="" method="POST">
        {% csrf_token %}
        {% if SELF_FEE %}
            <h3>{{item.product_name}} : ￥{{item.product_price_with_fee}}</h3>
        {% else %}
            {% if item.seller == userdata %}
                <h3>{{item.product_name}} : ￥{{item.product_price}}</h3>
            {% else %}
                <h3>{{item.product_name}} : ￥{{item.product_price_with_fee}}</h3>
            {% endif %}
        {% endif %}
        
        <input type="submit" class="button" value="買う">
    </form>
    {% endif %}
{% endblock main %}

templates/jihanki/dev.html
{% extends "base.html" %} {% block hero %}
<h1>金額管理</h1>
<p>開発者専用ページ</p>
{% endblock hero %} {% block main %}
<h3>D税 : ￥{{d_fee}}</h3>
<h3>未購入 : ￥{{item_money}}</h3>
{% for um in users_money %}
<p>
	{{um.username}} : {{um.money}}<br>
	<a class="button" href="{% url 'jihanki:paymentOut' um.pk %}">出金</a>
</p>

{% endfor %} {% endblock main %}

templates/jihanki/index.html
{% extends "base.html" %}

{% block hero %}
<h1>D組自販機へようこそ！</h1>
<p>つかえよつかえよ</p>
<a onclick="more_info()" class="button" href="#">もっと詳しく</a>
<a onclick="contact()" class="button success" href="#">お問い合わせ</a>
{% endblock hero %}


{% block main %}
<div class="row small-up-1 medium-up-2 large-up-3">
	<div class="tbpadding column column-block">
		<h3>売るためのページ</h3>
		<p>売れ売れ売れ売れ売れ売れ売れ売れ売れ</p>
		<a class="button" href="{% url 'jihanki:sellview' %}">売る</a><br>
	</div>

	<div class="tbpadding column column-block">
		<h3>買うためのページ</h3>
		<p>買え買え買え買え買え買え買え買え買え</p>
		<a class="button" href="{% url 'jihanki:buy' %}">買う</a><br>
	</div>

	<div class="tbpadding column column-block">
		<h3>今までのログ</h3>
		<p>ログログログログログログログログログ</p>
		<a class="button" href="{% url 'jihanki:log' %}">Log</a><br>
	</div>

	<div class="tbpadding column column-block">
		<h3>ニュース</h3>
		<p>ニュースニュースニュースニュースニュース</p>
		<a class="button" href="{% url 'jihanki:news' %}">ニュース</a><br>
	</div>
</div>
{% endblock main %}



templates/jihanki/log.html

{% extends "base.html" %}

{% block hero %}
<h1>ログ</h1>
<p>D組税　合計： <b>￥{{ d_fee }}</b></p>
{% if userdata.is_staff %}
<a class="button" href="{% url 'jihanki:dev' %}">金額管理</a>
{% endif %}
{% endblock hero %}

{% block main %}
<div class="row">
	<div class="small-12 large-12 columns">
		{% for log in logs %}
		{{log.deleted_date.day|default:""}}{% if log.deleted_date %}|{% endif %}{{log.deleted_date.time|default:""}}{% if log.deleted_date %} -> {% endif %}{{ log.product_name }} : ￥{{ log.product_price_with_fee }} <br>
		{% endfor %}
		<a class="button alert" style="margin-top: 50px" href="{% url 'jihanki:index' %}">戻る</a>
	</div>
</div>
{% endblock main %}

templates/jihanki/news.html
{% extends "base.html" %}

{% block hero %}
<h1>ニュース</h1>
<p>最近のアップデートなど</p>
{% endblock hero %}

{% block main %}
	{% for news in News %}
	<div class="callout">
		<h3>{{news.title}}</h3>
		<p>{{news.message}}</p>
	</div>
	{% endfor %}
{% endblock main %}

templates/jihanki/payment_in.html
{% extends "base.html" %}

{% block hero %}
<h1>入金</h1>
<p>お金入れろや！</p>
{% endblock hero %}

{% block main %}
{% if OK %}
	<h2>入金が完了しました</h2>
	<p>貯金箱に金絶対いれとけよ</p>
	<a class="button" href="{% url 'jihanki:index' %}">戻る</a>
{% else %}
	<form action="" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<h3>入金する金額を入力してください</h3>
		<div>金額
			<input type="number" name="price" value="0">
		</div>
		<div class="metadata">
			<input type="number" name="itemlen" value="{{ itemlen }}">
			<input type="number" name="loglen" value="{{ loglen }}">
		</div>
		<div>
			<div class="float-left">
				<a class="button" href="{% url 'jihanki:index' %}">戻る</a>
			</div>
			<div class="float-right">
				<input type="submit" class="button success" value="入金">
			</div>
		</div>
	</form>
{% endif %}
{% endblock main %}

templates/jihanki/payment_out.html
{% extends "base.html" %}

{% block hero %}
<h1>{{ user }}の出金</h1>
<p>お金だせや！</p>
{% endblock hero %}

{% block main %}
{% if OK %}
	<h2>出金が完了しました</h2>
	<p>取り出しとけよ</p>
	<a class="button" href="{% url 'jihanki:index' %}">戻る</a>
{% else %}
	<form action="" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<h3>出金する金額を入力してください</h3>
		<h4 style="color:red">￥{{balance}}まで</h4>
		<div>金額
			<input type="number" name="price" value="0">
		</div>
		<div class="metadata">
			<input type="number" name="itemlen" value="{{ itemlen }}">
			<input type="number" name="loglen" value="{{ loglen }}">
		</div>
		<div>
			<div class="float-left">
				<a class="button" href="{% url 'jihanki:index' %}">戻る</a>
			</div>
			<div class="float-right">
				<input type="submit" class="button success" value="出金">
			</div>
		</div>
	</form>
{% endif %}
{% endblock main %}

templates/jihanki/sell.html
{% extends "base.html" %}

{% block hero %}
<h1>いろいろと売っていきましょう！</h1>
<p>売ってけ売ってけ</p>
{% endblock hero %}

{% block main %}
<div class="row">
    <div class="small-12 large-12 columns">
        {% if OK %}
        <h3>買えるものに追加されました！</h3>
        <p>みんなが分かる場所においてください。</p>
        <a class="button alert float-left" href="{% url 'jihanki:index' %}">戻る</a>
        {% else %}
        <div class="row">
            <div class="mediam-12 columns">
                <h1>売る</h1>
                <h3>売ってけ</h3>
            </div>
        </div>
        
        <form action="" method="POST">
            {% csrf_token %}
            <label>商品名
                <input type="text" placeholder="商品名" name="product" required>
            </label>

            <label>値段（自動的に税がかかります）
                <input type="number" placeholder="値段" name="price" required>
            </label>

            <label>個数
                <input type="number" placeholder="個数" name="qt" value="1" required>
            </label>

            <div class="metadata">
                <input type="number" name="itemlen" value="{{ itemlen }}">
                <input type="number" name="loglen" value="{{ loglen }}">
            </div>

            <a class="button float-left" href="{% url 'jihanki:index' %}">戻る</a>
            <input class="button float-right success" type="submit" value="売る">
        </form>
        {% endif %}
    </div>
    <div class="small-0 large-2 columns"></div>
</div>
{% endblock main %}