urls.py
from django.conf.urls import url
from . import views

from rest_framework.urlpatterns import format_suffix_patterns

app_name = "jihanki"

urlpatterns = [
    # /
    # /jihanki/*
    url(r'^$',views.index,name="index"),
    url(r'^index/$',views.index,name="subindex"),
    
    url(r'^sell/$',views.SellView.as_view(),name="sellview"),

    # url(r'^sell/post/$',views.sellpost,name="sellpost"),
    # /jihanki/sell
    # url(r'^sell/priv/$',views.sell,name="sell"),

    # /jihanki/buy/post/<product_id>/
    url(r'^buyconfirm/(?P<pk>[0-9]+)/$',views.BuyConfirmView.as_view(),name="buyconfirm"),
    # /jihanki/buy
    url(r'^buy/$',views.BuyView.as_view(),name="buy"),

    url(r'^log/$',views.log,name="log"),

    url(r'^news/$',views.news,name="news"),

    url(r'^payment/in/$',views.PaymentInView.as_view(),name="paymentIn"),

    url(r'^dev/$',views.DevView.as_view(),name="dev"),

    url(r'^payment/out/(?P<pk>[0-9]+)/$',views.PaymentOutView.as_view(),name="paymentOut"),

    url(r'^deleteitem/(?P<pk>[0-9]+)/$',views.DeleteItemView.as_view(),name="deleteItem"),

    url(r'^itemlist/$',views.ItemList.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

templates/base.html
<!DOCTYPE html>
<html lang="jp">

<head>
	<title>{% block title %}XD Corp.{% endblock title %}</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'foundation/css/foundation.min.css' %}">
	<link rel="stylesheet" href="{% static 'jihanki/css/general.css' %}">
	<script src="{% static 'foundation/js/vendor/jquery.js' %}"></script>
	<script src="{% static 'foundation/js/vendor/foundation.min.js' %}"></script>
	<script src="{% static 'foundation/js/vendor/what-input.js' %}"></script>
	<script src="{% static 'jihanki/js/index.js' %}"></script>

	<!-- ***************GENERAL*************** -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="shortcut icon" href="{% static 'favicon.ico' %}"> 

</head>

<body>
	<div class="off-canvas-wrapper">
		<!-- ***************Off Canvas***************** -->
		<div class="off-canvas position-left nav-mobile-off-canvas" id="offCanvas" data-off-canvas>
			{% if userdata %}
			<ul class="dropdown menu" data-dropdown-menu>
				{% comment %}
				<li><a href="{% url 'jihanki:paymentIn' %}">￥{{ money }}</a></li>{% endcomment %}
				<a href="" class="user-info"><strong>{{ userdata.username }}</strong>さん</a>
				<ul class="menu vertical">
					<li><a href="{% url 'jihanki:paymentIn' %}">入金</a></li>
					<li><a href="#" class="out">出金</a></li>
					<li><a href="{% url 'xdmain:logout' %}">ログアウト</a></li>
				</ul>
			</ul>

			{% else %}
			<ul class="dropdown menu" 　data-dropdown-menu>
				<li><a href="{% url 'xdmain:login' %}">ログイン</a></li>
				<li><a href="{% url 'xdmain:register' %}">アカウント作成</a></li>
			</ul>
			{% endif %}
			<hr>
			<ul class="menu">
				<li><a href="{% url 'jihanki:index' %}">自動販売機</a></li>
			</ul>
		</div>

		<div class="off-canvas-content" data-off-canvas-content>

			<!-- ***************NAV*************** -->
			<nav class="nav">
				<div class="title-bar nav-mobile">
					<div class="title-bar-left">
						<button class="menu-icon" type="button" data-toggle="offCanvas"></button>
						<span class="title-bar-title">XD Copporation</span>
					</div>
					{% if userdata %}
					<div class="title-bar-right">
						<a href="{% url 'jihanki:paymentIn' %}">￥{{ money }}</a>
					</div>
					{% endif %}
				</div>

				<div class="top-bar nav-desktop">
					<div class="wrap">
						<div class="top-bar-left">
							<ul class="dropdown menu" data-dropdown-menu>
								<li class="menu-text">
									<h3>XD Corporation</h3>
								</li>
								<li><a href="{% url 'jihanki:index' %}">自動販売機</a></li>
							</ul>
						</div>
						<div class="top-bar-right">
							{% if userdata %}
							<ul class="dropdown menu" data-dropdown-menu>
								<li><a href="{% url 'jihanki:paymentIn' %}">￥{{ money }}</a></li>
								<li class="user-dropdown">
									<a href="" class="user-info"><strong>{{ userdata.username }}</strong>さん</a>
									<ul class="menu vertical">
										<li><a href="{% url 'jihanki:paymentIn' %}">入金</a></li>
										<li><a href="#" class="out">出金</a></li>
										<hr>
										<li><a href="{% url 'xdmain:logout' %}">ログアウト</a></li>
									</ul>
								</li>
							</ul>

							{% else %}
							<ul class="dropdown menu" 　data-dropdown-menu>
								<li><a href="{% url 'xdmain:login' %}">ログイン</a></li>
								<li><a href="{% url 'xdmain:register' %}">アカウント作成</a></li>
							</ul>
							{% endif %}
						</div>
					</div>
				</div>
			</nav>

			<section class="hero">
				<div class="wrap">
					{% block hero %} {% endblock hero %}
				</div>
			</section>

			<section class="main">
				<div class="wrap tbpadding">
					{% block main %} {% endblock main %}
				</div>
			</section>

			<footer>
				<div class="wrap">
					{% block footer %}
					<div class="row">
						<div class="small-6 large-6 columns">
							<blockquote>
								ベータとして稼働開始！
								<cite>ダニエル</cite>
							</blockquote>
						</div>
						<div class="small-6 large-6 columns">
							<p class="float-right">Designed with <a href="http://foundation.zurb.com/">Foundation</a></p>
						</div>
					</div>
					{% endblock footer %}
				</div>
			</footer>
		</div>
	</div>


	<script>
		$(document).foundation()
	</script>
</body>

</html>